In [1]:
import numpy as np
import pandas as pd

In [2]:
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

In [3]:
def stepFunction(t):
    if t >= 0:
        return 1
    return 0

In [4]:
def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

In [5]:
# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    incorrect_predict = 0

    for i, x_i in enumerate(X):
        y_hat = prediction(x_i,W,b)
        if y[i] != y_hat:
            incorrect_predict+=1        
            if y_hat==1: # incorrect positive
                W[0] -= X[i][0]*learn_rate
                W[1] -= X[i][1]*learn_rate
                b -= learn_rate
            elif y_hat==0: # incorrect negative
                W[0] += X[i][0]*learn_rate
                W[1] += X[i][1]*learn_rate
                b += learn_rate    

    return W, b, incorrect_predict
    

In [6]:
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b, incorrect_predict = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
        print('Epoch: ', i, ' - incorrect predictions', incorrect_predict)
    return boundary_lines

In [7]:
df = pd.read_csv('data.csv', header=None)

In [8]:
X=df.iloc[:, 0:2]
X = X.values

In [9]:
X[:3]

array([[ 0.78051 , -0.063669],
       [ 0.28774 ,  0.29139 ],
       [ 0.40714 ,  0.17878 ]])

In [10]:
y = df.iloc[:, 2]
y = y.values

In [11]:
y[:3]

array([1, 1, 1], dtype=int64)

In [12]:
boundary_lines = trainPerceptronAlgorithm(X, y, learn_rate=0.005, num_epochs=500)

Epoch:  0  - incorrect predictions 50
Epoch:  1  - incorrect predictions 50
Epoch:  2  - incorrect predictions 50
Epoch:  3  - incorrect predictions 50
Epoch:  4  - incorrect predictions 50
Epoch:  5  - incorrect predictions 30
Epoch:  6  - incorrect predictions 9
Epoch:  7  - incorrect predictions 9
Epoch:  8  - incorrect predictions 10
Epoch:  9  - incorrect predictions 9
Epoch:  10  - incorrect predictions 10
Epoch:  11  - incorrect predictions 10
Epoch:  12  - incorrect predictions 10
Epoch:  13  - incorrect predictions 10
Epoch:  14  - incorrect predictions 10
Epoch:  15  - incorrect predictions 10
Epoch:  16  - incorrect predictions 9
Epoch:  17  - incorrect predictions 9
Epoch:  18  - incorrect predictions 8
Epoch:  19  - incorrect predictions 8
Epoch:  20  - incorrect predictions 8
Epoch:  21  - incorrect predictions 8
Epoch:  22  - incorrect predictions 8
Epoch:  23  - incorrect predictions 8
Epoch:  24  - incorrect predictions 8
Epoch:  25  - incorrect predictions 8
Epoch:  2

Epoch:  322  - incorrect predictions 8
Epoch:  323  - incorrect predictions 8
Epoch:  324  - incorrect predictions 8
Epoch:  325  - incorrect predictions 8
Epoch:  326  - incorrect predictions 8
Epoch:  327  - incorrect predictions 8
Epoch:  328  - incorrect predictions 8
Epoch:  329  - incorrect predictions 7
Epoch:  330  - incorrect predictions 8
Epoch:  331  - incorrect predictions 8
Epoch:  332  - incorrect predictions 8
Epoch:  333  - incorrect predictions 8
Epoch:  334  - incorrect predictions 8
Epoch:  335  - incorrect predictions 8
Epoch:  336  - incorrect predictions 8
Epoch:  337  - incorrect predictions 8
Epoch:  338  - incorrect predictions 8
Epoch:  339  - incorrect predictions 8
Epoch:  340  - incorrect predictions 8
Epoch:  341  - incorrect predictions 7
Epoch:  342  - incorrect predictions 8
Epoch:  343  - incorrect predictions 8
Epoch:  344  - incorrect predictions 8
Epoch:  345  - incorrect predictions 8
Epoch:  346  - incorrect predictions 8
Epoch:  347  - incorrect 

In [13]:
boundary_lines[-1]

(array([-0.68316315]), array([0.82218582]))